### ISSUE TITLE
拖动地图时会出现偏移

### ISSUE THREAD

**Issue by ALein** [wangbingqian110/openlayers_echart#1]
你好，我看了代码，大概意思是生成一张画布，然后放到地图的viewport中，（不知道我这样理解对不对）这样操作会导致一个问题，就是我拖动地图时，画布这一层不能完全随着地图动，会出现一定的位置偏移，尤其是在比较快速的拖动时，请问有比较好的办法解决这个问题吗？

**Comment by wangbingqian110** [comment]
你好，因为这段时间忙于其他事情，所以很抱歉这么久才回你的消息。
这个问题确实存在，移动地图完成ECharts图层的刷新是利用Openlayers中的绑定事件pointerdrag来完成的，我尝试过另外几个事件，例如：pointermove、moveend等，均达不到预期的效果。相比之下，利用pointerdrag的效果是最好的。
在我这边如果不是飞快的拖动地图偏移不是很明显，你那边是很明显吗？

**Comment by wangbingqian110** [comment]
> 你好，我看了代码，大概意思是生成一张画布，然后放到地图的viewport中，（不知道我这样理解对不对）这样操作会导致一个问题，就是我拖动地图时，画布这一层不能完全随着地图动，会出现一定的位置偏移，尤其是在比较快速的拖动时，请问有比较好的办法解决这个问题吗？

@ALein 我更新了一下代码，将pointerdrag绑定换成了postrender，解决了这个问题，请看是否可以了。
