### ISSUE TITLE
缺少清除实例的方法

### ISSUE THREAD

**Issue by Dzxwind** [wangbingqian110/openlayers_echart#2]
感谢作者提供了一个非常棒的插件。
在实际使用中，发现了一个问题。在源码中并没有找到关于清除echarts实例的方法，使用原生的dispose()方法会报找不到getWith()的错误。
于是，我采用了清除DOM的方式，但是当我重复render的时候，地图会变得越来越卡，echarts叠加越来越多。
因此，希望作者能够添加一个清除的方法以完善这个非常棒的插件！！！

**Comment by wangbingqian110** [comment]
谢谢您的提醒，都怪我的疏忽，竟然这样一个至关重要的功能都没有。我已经将此方法更新到最新版本，方法名为clear。
您所遇到的geiWith()的错误是因为，虽然用Echarts原生的dispose方法销毁了对象，但是在OpenLayers所绑定的postrender事件中还是会调用Echart的setOption方法。

**Comment by Dzxwind** [comment]
我已经通过npm更新了依赖，但是使用clear方法之后，似乎并不能清除掉echarts实例，而且我确信已经执行了这个方法。。。
我这里的代码是这样的：
```
// 渲染的方法
oe = new ADLayer(lineOption, olMap, echarts);
oe.render();
***
***
***
***
***
// 清除的方法
oe.clear();
```
应该没有其他需要做的吧。。
还是说需要配合清除DOM的方法使用？

**Comment by wangbingqian110** [comment]
> 我已经通过npm更新了依赖，但是使用clear方法之后，似乎并不能清除掉echarts实例，而且我确信已经执行了这个方法。。。
> 我这里的代码是这样的：
> 
> ```
> // 渲染的方法
> oe = new ADLayer(lineOption, olMap, echarts);
> oe.render();
> ***
> ***
> ***
> ***
> ***
> // 清除的方法
> oe.clear();
> ```
> 应该没有其他需要做的吧。。
> 还是说需要配合清除DOM的方法使用？

不好意思，上个版本发布错了，我修改了一下，这次应该没有问题了。

**Comment by Dzxwind** [comment]
可以了，现在也不卡了，谢谢啦！！！
