### ISSUE TITLE
您好，散点图默认会覆盖掉openlayers 的地图，请问这是为什么？

### ISSUE THREAD

**Issue by yangdachu** [wangbingqian110/openlayers_echart#3]
![image](https://user-images.githubusercontent.com/23580181/49073708-02acbf00-f26e-11e8-8243-22d5bcb8ba31.png)

![image](https://user-images.githubusercontent.com/23580181/49073827-46072d80-f26e-11e8-97ea-f30ac342a60f.png)

这个是我的测试代码，麻烦您帮我看下可以吗？

**Comment by yangdachu** [comment]
![image](https://user-images.githubusercontent.com/23580181/49073827-46072d80-f26e-11e8-97ea-f30ac342a60f.png)

**Comment by yangdachu** [comment]
http://echarts.baidu.com/examples/editor.html?c=map-polygon 我想实现这个效果

**Comment by wangbingqian110** [comment]
可能回复的稍晚，不好意思。我从您给的截图中来看，像是没有用到插件中的方法。您是不是直接使用的echerts官方给出的方法呢？
应该这样用：
`var oe = new ADLayer(option,map,echarts) ;
oe.render()`
